'''
faca um programa que leia nome e a media
de um aluno, guardando tambem a situacao
em um dicionario. no final, mostre o conteudo
estruturado na tela.

saida:
nome e igual a ...
media e igual a ...
media e igual a ...
situacao e igual a ...
'''