'''
crie um programa onde 4 jogadores joguem um
dado e tenham resultados aleatorios. guarde
esses resultados em um dicionario em ordem, 
sabendo que o vencedor tirou o maior numero
no dado.

saida:

valores sorteados
o jogador 1 tirou ...
o jogador 2 tirou ...
o jogador 3 tirou ...
o jogador 4 tirou ...
ranking dos jogadores
o 1o lugar: jogador ... com ...
o ...
'''